backend:
  name: git-gateway
  # change repo to your git repository url
  repo: ana-vela/netlify-blog
  branch: main
  local_backend:
    url: http://localhost:8082/api/v1
    allowed_hosts: ['192.168.0.1']
publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: Settings
    files:
      - name: config
        label: Config
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Site Title
            required: true
          - widget: string
            name: siteUrl
            label: Website URL
            required: true
          - widget: text
            name: description
            label: Description
            default: ''
            required: false
          - widget: object
            name: home
            label: Homepage Options
            fields:
              - widget: string
                name: title
                label: Title
                default: ''
                required: false
              - widget: markdown
                name: description
                label: Description
                default: ''
                required: false

  - name: pages
    label: Pages
    files:
      - name: about
        label: About
        file: _data/site/content/about.md
        fields:
          - { name: body, label: Body, widget: markdown }
          # - { label: Template, name: template, widget: hidden, default: BlogPost }
          - label: Featured Image
            name: thumbnail
            widget: image
            hint: "Image size 1280x800 works best :)"
            required: false
            media_library:
            config:
              multiple: false
          - name: path
            label: Path
            widget: string
            pattern: [/, "Path must start with /"]
            hint: "Path must start with /"
          - { name: title, label: Title }
  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{slug}}
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - name: path
        label: Path
        widget: string
        pattern: [/, "Path must start with /"]
        hint: "Path must start with /"
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
      - { name: type, label: type, default: post, widget: hidden}
  - name: projects
    label: Projects
    folder: _data/projects
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: ProjectsPost,
        }
      - name: path
        label: Path
        widget: string
        pattern: [/, "Path must start with /"]
        hint: "Path must start with /"
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
      - { name: type, label: type, default: projects, widget: hidden}